# Generated by Django 5.2.9 on 2025-12-19 14:30

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], default='Student', max_length=10, verbose_name='Role')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='Gender')),
                ('biography', models.TextField(blank=True, max_length=500, null=True, verbose_name='Biography')),
                ('education', models.TextField(blank=True, max_length=150, null=True, verbose_name='Education')),
                ('extra_info', models.TextField(blank=True, max_length=300, null=True, verbose_name='Extra Information')),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID')),
                ('eitaa_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Eitaa ID')),
                ('instagram_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram ID')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visible', models.BooleanField(default=True, verbose_name='Profile visible')),
                ('email_on_login', models.BooleanField(default=False, verbose_name='Email on login')),
                ('email_on_payment', models.BooleanField(default=False, verbose_name='Email on payment')),
                ('sms_on_payment', models.BooleanField(default=True, verbose_name='SMS on payment')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='09123456789', help_text='Example: 09123456789', max_length=11, unique=True, validators=[users.models.validate_user_phone], verbose_name='Phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.PositiveIntegerField(default=10, help_text='For evaluating user rank', verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_user_usernam_65d164_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_user_phone_9474e8_idx'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
