# Generated by Django 5.2.9 on 2026-01-03 20:14

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_usersettings_user_phone_user_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='extra_info',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Province/City'),
        ),
        migrations.AddField(
            model_name='profile',
            name='had_other_classes',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Had other classes: Where'),
        ),
        migrations.AddField(
            model_name='profile',
            name='invited_by',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Invited by'),
        ),
        migrations.AddField(
            model_name='profile',
            name='memorized',
            field=models.TextField(blank=True, help_text='How much Quran this person memorized.', max_length=300, null=True, verbose_name='Memorized'),
        ),
        migrations.AddField(
            model_name='profile',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[users.models.validate_national_code], verbose_name='National Code'),
        ),
    ]
