# Generated by Django 5.2.9 on 2026-01-07 07:07

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_gender_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, validators=[users.models.validate_email_address], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=60, validators=[users.models.validate_name], verbose_name='Name'),
        ),
    ]
