# Generated by Django 5.2.9 on 2026-04-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_image'),
        ('users', '0005_alter_user_email_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course_history',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', to='courses.course', verbose_name='Course History'),
        ),
    ]
