# Generated by Django 5.2.9 on 2026-06-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_course_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
    ]
