# Generated by ChatGPT on 2026-05-19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Blog ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='Slug')),
                ('short_description', tinymce.models.HTMLField(verbose_name='Short Description')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('conclusion', tinymce.models.HTMLField(blank=True, verbose_name='Conclusion')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog/thumbnails/', verbose_name='Thumbnail')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('ttr', models.PositiveSmallIntegerField(default=1, verbose_name='Time To Read (Minutes)')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='Category')),
                ('saved_by', models.ManyToManyField(blank=True, related_name='saved_blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Saved By')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('content', models.TextField(verbose_name='Content')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost', verbose_name='Post')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.blogcomment', verbose_name='Reply To')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Blog Comment',
                'verbose_name_plural': 'Blog Comments',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.blogtag', verbose_name='Tags'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_visible', 'published_at'], name='blog_blogpo_is_visi_44e4b3_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['author', '-created_at'], name='blog_blogpo_author__b2daf4_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['view_count', '-created_at'], name='blog_blogpo_view_co_5be764_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='blog_blogpo_slug_5f45c9_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['title'], name='blog_blogpo_title_d315cf_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['post', 'created_at'], name='blog_blogco_post_id_2fa167_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['user', '-created_at'], name='blog_blogco_user_id_6bbf8f_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['reply_to'], name='blog_blogco_reply_t_c4f91a_idx'),
        ),
    ]
