# Generated by Django 5.2.9 on 2026-05-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blogcomment',
            new_name='blog_blogco_post_id_9d37d4_idx',
            old_name='blog_blogco_post_id_2fa167_idx',
        ),
        migrations.RenameIndex(
            model_name='blogcomment',
            new_name='blog_blogco_user_id_43af83_idx',
            old_name='blog_blogco_user_id_6bbf8f_idx',
        ),
        migrations.RenameIndex(
            model_name='blogcomment',
            new_name='blog_blogco_reply_t_081e90_idx',
            old_name='blog_blogco_reply_t_c4f91a_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_blogpo_is_visi_536411_idx',
            old_name='blog_blogpo_is_visi_44e4b3_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_blogpo_author__61fe3f_idx',
            old_name='blog_blogpo_author__b2daf4_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_blogpo_view_co_48fdd5_idx',
            old_name='blog_blogpo_view_co_5be764_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_blogpo_slug_361555_idx',
            old_name='blog_blogpo_slug_5f45c9_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_blogpo_title_2aa4d1_idx',
            old_name='blog_blogpo_title_d315cf_idx',
        ),
    ]
