# Generated by Django 5.2.9 on 2026-06-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_blogco_post_id_2fa167_idx_blog_blogco_post_id_9d37d4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=280, unique=True, verbose_name='Slug'),
        ),
    ]
