# Generated by Django 5.2.9 on 2025-12-27 16:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Transaction ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)], verbose_name='Paid Amount')),
                ('currency', models.CharField(choices=[('IRR', 'Rial'), ('IRT', 'Toman')], max_length=10, verbose_name='Currency')),
                ('transaction_type', models.CharField(choices=[('gateway', 'Gateway'), ('transfer', 'Transfer'), ('cash', 'Cash')], max_length=10, verbose_name='Transaction Type')),
                ('transaction_reason', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('fee', 'Fee'), ('adjustment', 'Adjustment')], max_length=20, verbose_name='Transaction Reason')),
                ('transaction_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], max_length=20, verbose_name='Transaction Status')),
                ('provider', models.CharField(max_length=100, verbose_name='Provider')),
                ('tracking_id', models.CharField(max_length=200, unique=True, verbose_name='Tracking ID')),
                ('provider_payload', models.JSONField(blank=True, null=True, verbose_name='Provider Payload')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='IP Address, Device Info', verbose_name='Transaction metadata')),
                ('description', models.TextField(blank=True, help_text='Any thing about the transaction like failure reason.', max_length=300, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'indexes': [models.Index(fields=['user', 'created_at'], name='payment_tra_user_id_8623b0_idx'), models.Index(fields=['transaction_status'], name='payment_tra_transac_3e61f9_idx'), models.Index(fields=['tracking_id'], name='payment_tra_trackin_eaa0a0_idx')],
            },
        ),
    ]
