# Generated by Django 5.2.9 on 2025-12-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_transaction_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='locked_in',
            field=models.BooleanField(default=False, verbose_name='Locked in'),
        ),
    ]
