# Generated by Django 5.2.9 on 2026-06-04 16:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_page', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Start Page')),
                ('end_page', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='End Page')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('time_to_finish', models.DateField(verbose_name='Target Finish Date')),
                ('time_freq', models.CharField(choices=[('per_day', 'Per Day'), ('per_two_days', 'Per Two Days')], default='per_day', max_length=20, verbose_name='Study Frequency')),
                ('reading_freq', models.CharField(choices=[('half_page', 'Half Page'), ('full_page', 'Full Page')], default='full_page', max_length=20, verbose_name='Reading Amount per Session')),
                ('review_freq', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Review Every N Pages')),
                ('user_day_availability', models.CharField(choices=[('odd_days', 'Odd Days (Sun, Tue, Thu)'), ('even_days', 'Even Days (Sat, Mon, Wed)')], max_length=20, verbose_name='Available Days')),
                ('user_time_availability', models.CharField(choices=[('morning', '9 AM – 11 AM'), ('afternoon', '3 PM – 5 PM'), ('evening', '7 PM – 9 PM')], max_length=20, verbose_name='Preferred Time Slot')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Plan Status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('_steps_generated', models.BooleanField(default=False, editable=False, verbose_name='Steps Generated')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_plans', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_plans', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Automatic Plan',
                'verbose_name_plural': 'Automatic Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminCallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(verbose_name='Call Notes')),
                ('call_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Call Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_call_logs', to=settings.AUTH_USER_MODEL, verbose_name='Called By')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='automatic_class.automaticplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Admin Call Log',
                'verbose_name_plural': 'Admin Call Logs',
                'ordering': ['-call_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, verbose_name='User Notes')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('plan_created', 'Plan Created'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Class Request',
                'verbose_name_plural': 'Class Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='automaticplan',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan', to='automatic_class.classrequest', verbose_name='Class Request'),
        ),
        migrations.CreateModel(
            name='PlanStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField(verbose_name='Step Number')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Scheduled Date')),
                ('step_type', models.CharField(choices=[('memorize', 'Memorize'), ('review', 'Review'), ('final_review', 'Final Review')], max_length=20, verbose_name='Step Type')),
                ('page_start', models.PositiveIntegerField(verbose_name='Page Start')),
                ('page_end', models.PositiveIntegerField(verbose_name='Page End')),
                ('sub_part', models.CharField(choices=[('full', 'Full Page'), ('first_half', 'First Half'), ('second_half', 'Second Half')], default='full', max_length=20, verbose_name='Sub Part')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delayed', 'Delayed'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='Status')),
                ('is_delayed', models.BooleanField(default=False, help_text='True if this step was completed or carried over past its scheduled date.', verbose_name='Was Delayed')),
                ('original_scheduled_date', models.DateField(blank=True, help_text='Set when a pending step is pushed past its scheduled date.', null=True, verbose_name='Original Scheduled Date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('delay_reason', models.TextField(blank=True, verbose_name='Delay Reason')),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='automatic_class.automaticplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Plan Step',
                'verbose_name_plural': 'Plan Steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.AddIndex(
            model_name='classrequest',
            index=models.Index(fields=['user', 'status'], name='automatic_c_user_id_391edf_idx'),
        ),
        migrations.AddIndex(
            model_name='classrequest',
            index=models.Index(fields=['status', 'created_at'], name='automatic_c_status_5a72cc_idx'),
        ),
        migrations.AddIndex(
            model_name='automaticplan',
            index=models.Index(fields=['user', 'status'], name='automatic_c_user_id_1f00f1_idx'),
        ),
        migrations.AddIndex(
            model_name='planstep',
            index=models.Index(fields=['plan', 'scheduled_date'], name='automatic_c_plan_id_6e3574_idx'),
        ),
        migrations.AddIndex(
            model_name='planstep',
            index=models.Index(fields=['plan', 'status'], name='automatic_c_plan_id_3fc6cb_idx'),
        ),
        migrations.AddIndex(
            model_name='planstep',
            index=models.Index(fields=['scheduled_date', 'status'], name='automatic_c_schedul_097173_idx'),
        ),
    ]
