# Generated by Django 5.2.9 on 2026-06-20 11:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic_class', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticplan',
            name='extra_review_end_page',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Extra Review End Page'),
        ),
        migrations.AddField(
            model_name='automaticplan',
            name='extra_review_pages_per_session',
            field=models.PositiveIntegerField(default=0, verbose_name='Extra Review Pages per Session'),
        ),
        migrations.AddField(
            model_name='automaticplan',
            name='extra_review_start_page',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Extra Review Start Page'),
        ),
        migrations.AlterField(
            model_name='classrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Admin'), ('contacted', 'Contacted'), ('plan_created', 'Plan Created'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='planstep',
            name='step_type',
            field=models.CharField(choices=[('memorize', 'Memorize'), ('review', 'Review'), ('extra_review', 'Extra Review'), ('final_review', 'Final Review')], max_length=20, verbose_name='Step Type'),
        ),
        migrations.CreateModel(
            name='OnlineCallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_number', models.PositiveIntegerField(verbose_name='Session Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('no_answer', 'No Answer')], default='pending', max_length=20, verbose_name='Status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_call_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Marked By')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='automatic_class.automaticplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Online Call Session',
                'verbose_name_plural': 'Online Call Sessions',
                'ordering': ['session_number'],
                'unique_together': {('plan', 'session_number')},
            },
        ),
    ]
