# Generated by Django 5.2.9 on 2026-06-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic_class', '0002_automaticplan_extra_review_end_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active Plan'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Plan Status'),
        ),
    ]
