# Generated by Django 5.2.9 on 2026-08-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic_class', '0003_alter_automaticplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticplan',
            name='advance_completion_days',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='How many days ahead the user may complete steps. Empty disables pre-completion; 0 means unlimited.', null=True, verbose_name='Advance Completion Days'),
        ),
    ]
