# Generated by Django 5.2.9 on 2026-08-15 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic_class', '0004_automaticplan_advance_completion_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticplan',
            name='generate_call_sessions',
            field=models.BooleanField(default=True, verbose_name='Generate Call Sessions on Activation'),
        ),
        migrations.AddField(
            model_name='automaticplan',
            name='parent_plan',
            field=models.ForeignKey(blank=True, help_text='When set, this plan activates automatically once the parent plan completes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chained_plans', to='automatic_class.automaticplan', verbose_name='Chained From Plan'),
        ),
        migrations.AlterField(
            model_name='automaticplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('active', 'Active Plan'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Plan Status'),
        ),
        migrations.AlterField(
            model_name='automaticplan',
            name='time_to_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Target Finish Date'),
        ),
    ]
