# Generated by Django 5.2.9 on 2026-09-01 08:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_extra_review_fields_forward(apps, schema_editor):
    """Turn each plan's single extra_review_* triple into one ExtraReviewRange row."""
    AutomaticPlan = apps.get_model('automatic_class', 'AutomaticPlan')
    ExtraReviewRange = apps.get_model('automatic_class', 'ExtraReviewRange')

    plans = AutomaticPlan.objects.filter(
        extra_review_start_page__isnull=False,
        extra_review_end_page__isnull=False,
        extra_review_pages_per_session__gt=0,
    )
    ExtraReviewRange.objects.bulk_create([
        ExtraReviewRange(
            plan=plan,
            start_page=plan.extra_review_start_page,
            end_page=plan.extra_review_end_page,
            pages_per_session=plan.extra_review_pages_per_session,
            order=0,
        )
        for plan in plans
    ])


def copy_extra_review_fields_backward(apps, schema_editor):
    """Fold each plan's lowest-order range back into the single extra_review_* triple."""
    AutomaticPlan = apps.get_model('automatic_class', 'AutomaticPlan')

    for plan in AutomaticPlan.objects.all():
        first = plan.extra_review_ranges.order_by('order', 'created_at').first()
        if not first:
            continue
        plan.extra_review_start_page = first.start_page
        plan.extra_review_end_page = first.end_page
        plan.extra_review_pages_per_session = first.pages_per_session
        plan.save(update_fields=[
            'extra_review_start_page', 'extra_review_end_page', 'extra_review_pages_per_session',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('automatic_class', '0005_automaticplan_generate_call_sessions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraReviewRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_page', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Start Page')),
                ('end_page', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='End Page')),
                ('pages_per_session', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Pages per Session')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_review_ranges', to='automatic_class.automaticplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Extra Review Range',
                'verbose_name_plural': 'Extra Review Ranges',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['plan', 'order'], name='automatic_c_plan_id_af8070_idx')],
            },
        ),
        migrations.RunPython(copy_extra_review_fields_forward, copy_extra_review_fields_backward),
        migrations.RemoveField(
            model_name='automaticplan',
            name='extra_review_end_page',
        ),
        migrations.RemoveField(
            model_name='automaticplan',
            name='extra_review_pages_per_session',
        ),
        migrations.RemoveField(
            model_name='automaticplan',
            name='extra_review_start_page',
        ),
    ]
