# Generated by Django 5.2.9 on 2026-06-23 13:27

import django.core.validators
import django.db.models.deletion
import tinymce.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Quiz Category',
                'verbose_name_plural': 'Quiz Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('true_false', 'True / False')], default='multiple_choice', max_length=20, verbose_name='Question Type')),
                ('text', models.TextField(verbose_name='Question Text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('score', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Score')),
                ('time_to_answer', models.PositiveIntegerField(default=30, help_text='Contributes to the quiz global timer; not enforced per-question.', verbose_name='Time to Answer (seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500, verbose_name='Option Text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Question Option',
                'verbose_name_plural': 'Question Options',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='quiz/thumbnails/', verbose_name='Thumbnail')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10, verbose_name='Difficulty')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('randomize_question_order', models.BooleanField(default=False, verbose_name='Randomize Question Order')),
                ('max_attempts_per_user', models.PositiveIntegerField(default=0, help_text='0 means unlimited', verbose_name='Max Attempts Per User')),
                ('reveal_answers_during_quiz', models.BooleanField(default=False, verbose_name='Reveal Answers During Quiz')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('categories', models.ManyToManyField(blank=True, related_name='quizzes', to='quiz.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='Quiz'),
        ),
        migrations.CreateModel(
            name='QuizAccessRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('free', 'Free'), ('completed_quiz', 'Completed Quiz'), ('min_score', 'Minimum Score'), ('subscription', 'Subscription Required')], default='free', max_length=20, verbose_name='Requirement Type')),
                ('required_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Required Score')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requirements', to='quiz.quiz', verbose_name='Quiz')),
                ('required_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_by', to='quiz.quiz', verbose_name='Required Quiz')),
            ],
            options={
                'verbose_name': 'Quiz Access Requirement',
                'verbose_name_plural': 'Quiz Access Requirements',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Score')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='Correct Count')),
                ('incorrect_count', models.PositiveIntegerField(default=0, verbose_name='Incorrect Count')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Time Spent (seconds)')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='in_progress', max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct')),
                ('time_taken', models.PositiveIntegerField(default=0, verbose_name='Time Taken (seconds)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='quiz.question', verbose_name='Question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='quiz.questionoption', verbose_name='Selected Option')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizattempt', verbose_name='Attempt')),
            ],
            options={
                'verbose_name': 'Attempt Answer',
                'verbose_name_plural': 'Attempt Answers',
            },
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_active', 'created_at'], name='quiz_quiz_is_acti_66315a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'order'], name='quiz_questi_quiz_id_f13328_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz'], name='quiz_quizat_user_id_2f0af4_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'status'], name='quiz_quizat_user_id_47c6be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attemptanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
