# Generated by Django 5.2.9 on 2026-06-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_add_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_retry_on_expiry',
            field=models.BooleanField(default=True, help_text='If enabled, expired (timed-out) attempts do not count against the attempt limit.', verbose_name='Allow Retry on Expiry'),
        ),
    ]
