# Generated by Django 5.2.9 on 2026-06-24 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_add_allow_retry_on_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='matching_answer',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Matching Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('true_false', 'True / False'), ('matching', 'Matching')], default='multiple_choice', max_length=20, verbose_name='Question Type'),
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('left_text', models.CharField(max_length=500, verbose_name='Left Text')),
                ('right_text', models.CharField(max_length=500, verbose_name='Right Text')),
                ('left_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('right_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='quiz.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Matching Pair',
                'verbose_name_plural': 'Matching Pairs',
                'ordering': ('order',),
                'indexes': [models.Index(fields=['question', 'order'], name='quiz_matchi_questio_267634_idx')],
            },
        ),
    ]
