# Generated by Django 5.2.9 on 2026-08-14 09:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSweepRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Run At')),
                ('files_deleted', models.PositiveIntegerField(default=0, verbose_name='Files Deleted')),
                ('bytes_freed', models.PositiveBigIntegerField(default=0, verbose_name='Bytes Freed')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Errors')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_sweep_runs', to=settings.AUTH_USER_MODEL, verbose_name='Run By')),
            ],
            options={
                'verbose_name': 'Media Sweep Run',
                'verbose_name_plural': 'Media Sweep Runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
