# Generated by Django 5.2.9 on 2026-01-07 07:07

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', django_resized.forms.ResizedImageField(crop=None, force_format=None, help_text='Recommended: 506×106 pixels', keep_meta=True, quality=100, scale=None, size=[506, 106], upload_to='footer/', verbose_name='Footer Logo')),
                ('description', models.TextField(max_length=600, verbose_name='Short Description')),
                ('rights', models.CharField(help_text='e.g., "All rights reserved. © 2026"', max_length=300, verbose_name='Copyright Text')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal reference (e.g., "Contact Page")', max_length=255, verbose_name='Internal Name')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('eitaa', 'ایتا'), ('bale', 'بله'), ('aparat', 'آپارات'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('youtube', 'Youtube'), ('facebook', 'Facebook'), ('x', 'X'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest')], max_length=50, verbose_name='Platform')),
                ('url', models.URLField(verbose_name='Profile URL')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['platform'],
            },
        ),
        migrations.CreateModel(
            name='FooterLinkColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Column Title')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Order')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='siteconfig.footer', verbose_name='Footer')),
            ],
            options={
                'verbose_name': 'Footer Link Column',
                'verbose_name_plural': 'Footer Link Columns',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FooterColumnLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='How this link appears in this column', max_length=100, verbose_name='Display Label')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Order')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_links', to='siteconfig.footerlinkcolumn', verbose_name='Column')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteconfig.link', verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Column Link',
                'verbose_name_plural': 'Column Links',
                'ordering': ['order', 'label'],
                'unique_together': {('column', 'link', 'order')},
            },
        ),
        migrations.CreateModel(
            name='FooterSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Order')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_items', to='siteconfig.footer', verbose_name='Footer')),
                ('social_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteconfig.socialmedialink', verbose_name='Social Media Link')),
            ],
            options={
                'verbose_name': 'Footer Social Media',
                'verbose_name_plural': 'Footer Social Media',
                'ordering': ['order', 'social_link__platform'],
                'unique_together': {('footer', 'social_link')},
            },
        ),
    ]
