# Generated by Django 5.2.9 on 2026-01-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footercolumnlink',
            name='label',
            field=models.CharField(blank=True, help_text='How this link appears in this column. Leave blank if you want to use link.name instead.', max_length=100, null=True, verbose_name='Display Label'),
        ),
    ]
