# Generated by Django 5.2.9 on 2026-01-08 08:56

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_alter_footercolumnlink_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNavbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1_title', models.CharField(max_length=100, verbose_name='Col 1 Title')),
                ('col2_title', models.CharField(max_length=100, verbose_name='Col 2 Title')),
                ('col3_title', models.CharField(max_length=100, verbose_name='Col 3 Title')),
                ('banner_title', models.CharField(max_length=100, verbose_name='Banner Col Title')),
                ('banner_link', models.URLField(verbose_name='Banner URL')),
                ('banner_img', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, help_text='367 * 320 pixels', keep_meta=True, quality=100, scale=None, size=[367, 320], upload_to='navbar_images/Col4/', verbose_name='Banner Image')),
                ('notification', models.CharField(blank=True, help_text='Shown under the mega-menu', max_length=255, null=True, verbose_name='Notification message')),
            ],
            options={
                'verbose_name': 'Site Navbar',
                'verbose_name_plural': 'Site Navbar',
            },
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='url',
            field=models.URLField(verbose_name='Platform URL/Link/ID'),
        ),
        migrations.CreateModel(
            name='SiteNavbarDescribedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='How this link appears in this column. Leave blank if you want to use link.name instead.', max_length=100, null=True, verbose_name='Display Label')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Order')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='siteconfig.link', verbose_name='Link')),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='siteconfig.sitenavbar', verbose_name='Navbar')),
            ],
            options={
                'verbose_name': 'Site Navbar Described',
                'verbose_name_plural': 'Site Navbar Described',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='SiteNavbarImageItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='How this link appears in this column. Leave blank if you want to use link.name instead.', max_length=100, null=True, verbose_name='Display Label')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Order')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('icon', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, help_text='40 * 40 pixels', keep_meta=True, quality=100, scale=None, size=[40, 40], upload_to='navbar_images/Col3/', verbose_name='Icon')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='siteconfig.link', verbose_name='Link')),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='siteconfig.sitenavbar', verbose_name='Navbar')),
            ],
            options={
                'verbose_name': 'Site Navbar Image Items',
                'verbose_name_plural': 'Site Navbar Image Items',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='SiteNavbarTitleOnlyItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='How this link appears in this column. Leave blank if you want to use link.name instead.', max_length=100, null=True, verbose_name='Display Label')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Order')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='siteconfig.link', verbose_name='Link')),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='siteconfig.sitenavbar', verbose_name='Navbar')),
            ],
            options={
                'verbose_name': 'Site Navbar Items',
                'verbose_name_plural': 'Site Navbar Items',
                'ordering': ('order',),
            },
        ),
    ]
