# Generated by Django 5.2.9 on 2026-02-23 09:36

import django.core.validators
import django.db.models.deletion
import django_resized.forms
import siteconfig.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0003_sitenavbar_alter_socialmedialink_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_title', models.CharField(max_length=100, verbose_name='Main Title')),
                ('landing_brushed_title', models.CharField(max_length=100, verbose_name='Brushed Title')),
                ('landing_description', models.TextField(max_length=600, verbose_name='Description')),
                ('landing_video', models.FileField(blank=True, null=True, upload_to='landing_contents/video', validators=[siteconfig.models.video_validator], verbose_name='Video Intro')),
                ('landing_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[386, 603], upload_to='landing_contents/image', verbose_name='Landing Image')),
                ('landing_message_title', models.CharField(max_length=60, verbose_name='Message Title')),
                ('landing_message_description', models.CharField(max_length=80, verbose_name='Message Description')),
                ('stat1_title', models.CharField(max_length=80, verbose_name='Stat #1 Title')),
                ('stat1_description', models.CharField(max_length=80, verbose_name='Stat #1 Description')),
                ('stat2_title', models.CharField(max_length=80, verbose_name='Stat #2 Title')),
                ('stat2_description', models.CharField(max_length=80, verbose_name='Stat #2 Description')),
                ('stat3_title', models.CharField(max_length=80, verbose_name='Stat #3 Title')),
                ('stat3_description', models.CharField(max_length=80, verbose_name='Stat #3 Description')),
                ('stat4_title', models.CharField(max_length=80, verbose_name='Stat #4 Title')),
                ('stat4_description', models.CharField(max_length=80, verbose_name='Stat #4 Description')),
                ('courses_title', models.CharField(max_length=100, verbose_name='Courses Section Title')),
                ('courses_description', models.TextField(max_length=200, verbose_name='Courses Section Description')),
                ('ad_title', models.CharField(max_length=100, verbose_name='Advertisement Title')),
                ('ad_description', models.TextField(max_length=300, verbose_name='Advertisement Description')),
                ('course_suggestions_title', models.CharField(max_length=100, verbose_name='Course Suggestion Title')),
                ('course_suggestions_description', models.TextField(max_length=200, verbose_name='Course Suggestion Description')),
                ('ux_title', models.CharField(max_length=100, verbose_name='User Experience Title')),
                ('ux_description', models.TextField(max_length=300, verbose_name='User Experience Description')),
                ('ux_top_users_enable', models.BooleanField(default=False, verbose_name='Show Selected Top Users')),
                ('ux_top_users_title', models.CharField(max_length=60, verbose_name='Top Users Title')),
                ('ux_comment1_text', models.TextField(max_length=400, verbose_name='User Comment #1 Text')),
                ('ux_comment1_rate', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='User Comment #1 Rate')),
                ('ux_comment2_text', models.TextField(max_length=400, verbose_name='User Comment #2 Text')),
                ('ux_comment2_rate', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='User Comment #2 Rate')),
                ('ad_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_ad_link', to='siteconfig.link', verbose_name='Advertisement Link')),
                ('landing_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_landing_link', to='siteconfig.link', verbose_name='Quick Start Link')),
                ('ux_comment1_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_page_comment1', to=settings.AUTH_USER_MODEL, verbose_name='User Comment #1 User')),
                ('ux_comment2_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_page_comment2', to=settings.AUTH_USER_MODEL, verbose_name='User Comment #2 User')),
                ('ux_top_users', models.ManyToManyField(blank=True, related_name='ux_top_users', to=settings.AUTH_USER_MODEL, verbose_name='Top Users List')),
            ],
            options={
                'verbose_name': 'Main Page',
                'verbose_name_plural': 'Main Page',
            },
        ),
    ]
