# Generated by Django 5.2.9 on 2026-02-24 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0004_mainpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='stat1_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_stat1_link', to='siteconfig.link', verbose_name='Stat #1 Link'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='stat2_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_stat2_link', to='siteconfig.link', verbose_name='Stat #2 Link'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='stat3_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_stat3_link', to='siteconfig.link', verbose_name='Stat #3 Link'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='stat4_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_stat4_link', to='siteconfig.link', verbose_name='Stat #4 Link'),
        ),
    ]
