# Generated by Django 5.2.9 on 2026-02-25 06:37

import django.db.models.deletion
import django_resized.forms
import siteconfig.models
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0005_mainpage_stat1_link_mainpage_stat2_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the FAQ. Lower number appears first.', verbose_name='Order')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ('order',),
            },
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='course_suggestions_description',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='course_suggestions_title',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='courses_description',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='courses_title',
        ),
        migrations.AddField(
            model_name='link',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Recommended: Maintain square aspect-ratio', keep_meta=True, null=True, quality=100, scale=None, size=[200, 200], upload_to='Links/', verbose_name='Link Logo'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='choice1_description',
            field=models.TextField(default='description', max_length=300, verbose_name='Choice #1 Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='choice1_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='1', force_format=None, help_text='Recommended: 235 * 200 pixel', keep_meta=True, quality=100, scale=None, size=[200, 200], upload_to='DualChoice/images', verbose_name='Choice #1 Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='choice1_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_choice1_link', to='siteconfig.link', verbose_name='Choice #1 Link'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='choice1_title',
            field=models.CharField(default='choice1 title', max_length=100, verbose_name='Choice #1 Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='choice2_description',
            field=models.TextField(default='choice2 description', max_length=300, verbose_name='Choice #2 Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='choice2_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='1', force_format=None, help_text='Recommended: 235 * 200 pixel', keep_meta=True, quality=100, scale=None, size=[200, 200], upload_to='DualChoice/images', verbose_name='Choice #2 Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='choice2_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_choice2_link', to='siteconfig.link', verbose_name='Choice #2 Link'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='choice2_title',
            field=models.CharField(default='1', max_length=100, verbose_name='Choice #2 Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='imaged_links_list',
            field=models.ManyToManyField(blank=True, related_name='custom_imaged_links', to='siteconfig.link', verbose_name='Custom Imaged Links List'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='top_courses_video',
            field=models.FileField(blank=True, upload_to='top_course_video/', validators=[siteconfig.models.video_validator], verbose_name='Top Course Video File'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='top_teachers_description',
            field=models.TextField(default='1', max_length=200, verbose_name='Top Teachers Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='top_teachers_list',
            field=models.ManyToManyField(blank=True, related_name='top_teachers', to=settings.AUTH_USER_MODEL, verbose_name='Top Teachers List'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='top_teachers_title',
            field=models.CharField(default='1', max_length=100, verbose_name='Top Teachers Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitenavbar',
            name='navbar_links',
            field=models.ManyToManyField(blank=True, related_name='navbar_links', to='siteconfig.link', verbose_name='Navbar Links'),
        ),
        migrations.AddField(
            model_name='sitenavbar',
            name='navbar_logo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='1', force_format=None, help_text='150 * 36 pixels', keep_meta=True, quality=100, scale=None, size=[150, 36], upload_to='navbar_images/logo/', verbose_name='Navbar Logo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Title')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, help_text='Recommended: 615 * 435', keep_meta=True, quality=100, scale=None, size=[200, 200], upload_to='information/images', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number appear first', verbose_name='Order')),
                ('mainpage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_boxes', to='siteconfig.mainpage', verbose_name='Main Page')),
            ],
            options={
                'verbose_name': 'Information Section',
                'verbose_name_plural': 'Information Sections',
                'ordering': ('order',),
            },
        ),
    ]
