# Generated by Django 5.2.9 on 2026-04-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0006_faq_remove_mainpage_course_suggestions_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(help_text='Recommended: 615 * 435', upload_to='information/images', verbose_name='Image'),
        ),
    ]
