# Generated by Django 5.2.9 on 2026-04-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0007_alter_information_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.FileField(help_text='Recommended: 615 * 435', upload_to='information/images', verbose_name='Image'),
        ),
    ]
