# Generated by Django 5.2.9 on 2026-04-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0008_alter_information_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='logo',
            field=models.FileField(blank=True, help_text='Recommended: Maintain square aspect-ratio', null=True, upload_to='Links/', verbose_name='Link Logo'),
        ),
    ]
