# Generated by Django 5.2.9 on 2026-04-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0009_alter_link_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='landing_image',
            field=models.FileField(help_text='Recommended: 386 * 603', upload_to='landing_contents/image', verbose_name='Landing Image'),
        ),
    ]
