# Generated by Django 5.2.9 on 2026-04-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0010_alter_mainpage_landing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='contact_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Contact Address'),
        ),
        migrations.AddField(
            model_name='footer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='footer',
            name='contact_hours',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contact Hours'),
        ),
        migrations.AddField(
            model_name='footer',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contact Phone'),
        ),
    ]
