# Generated by Django 5.2.9 on 2026-05-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0011_footer_contact_address_footer_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='feature1',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Feature #1'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='feature2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Feature #2'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='feature3',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Feature #3'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='icon1',
            field=models.FileField(blank=True, null=True, upload_to='landing_contents/icons', verbose_name='Feature Icon #1'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='icon2',
            field=models.FileField(blank=True, null=True, upload_to='landing_contents/icons', verbose_name='Feature Icon #2'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='icon3',
            field=models.FileField(blank=True, null=True, upload_to='landing_contents/icons', verbose_name='Feature Icon #3'),
        ),
    ]
