# Generated by Django 5.2.9 on 2026-05-20 15:49

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0012_mainpage_feature1_mainpage_feature2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitenavbar',
            name='navbar_logo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, help_text='Forced Size: 200 * 50 pixels', keep_meta=True, quality=100, scale=None, size=[200, 50], upload_to='navbar_images/logo/', verbose_name='Navbar Logo'),
        ),
    ]
