# Generated by Django 5.2.9 on 2026-05-20 16:01

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0013_alter_sitenavbar_navbar_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitenavbar',
            name='navbar_links',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='navbar_links', to='siteconfig.link', verbose_name='Navbar Links'),
        ),
    ]
