# Generated by Django 5.2.9 on 2026-05-20 18:57

import sortedm2m.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0015_fix_sortedm2m_navbar_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_section_title', models.CharField(max_length=255, verbose_name='Image Section Title')),
                ('image_section_top_right_image', models.FileField(blank=True, null=True, upload_to='aboutus/images/', verbose_name='Image Section Top Right Image')),
                ('image_section_bottom_right_image', models.FileField(blank=True, null=True, upload_to='aboutus/images/', verbose_name='Image Section Bottom Right Image')),
                ('image_section_middle_image', models.FileField(blank=True, null=True, upload_to='aboutus/images/', verbose_name='Image Section Middle Image')),
                ('image_section_bottom_left_image', models.FileField(blank=True, null=True, upload_to='aboutus/images/', verbose_name='Image Section Bottom Left Image')),
                ('image_section_box_title', models.CharField(max_length=100, verbose_name='Image Section Box Title')),
                ('image_section_box_description', models.TextField(max_length=300, verbose_name='Image Section Box Description')),
                ('info_section_title', models.CharField(max_length=255, verbose_name='Info Section Title')),
                ('info_section_description', tinymce.models.HTMLField(verbose_name='Info Section Description')),
                ('trust_logo_section_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Trust Logo Section Title')),
                ('info_section_information_boxes', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='aboutus_information_boxes', to='siteconfig.information', verbose_name='Info Section Information Boxes')),
                ('trust_logo_section_links', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='aboutus_trust_links', to='siteconfig.link', verbose_name='Trust Logo Section Links')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
