# Generated by Django 5.2.9 on 2026-05-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0016_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='info_section_information_boxes',
            field=models.ManyToManyField(blank=True, related_name='aboutus_information_boxes', to='siteconfig.information', verbose_name='Info Section Information Boxes'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='trust_logo_section_links',
            field=models.ManyToManyField(blank=True, related_name='aboutus_trust_links', to='siteconfig.link', verbose_name='Trust Logo Section Links'),
        ),
    ]
