# Generated by Django 5.2.9 on 2026-05-20 19:37

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0017_alter_aboutus_info_section_information_boxes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='info_section_information_boxes',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='aboutus_information_boxes', to='siteconfig.information', verbose_name='Info Section Information Boxes'),
        ),
    ]
