# Generated by Django 5.2.9 on 2026-05-20 19:39

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0018_alter_aboutus_info_section_information_boxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='trust_logo_section_links',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='aboutus_trust_links', to='siteconfig.link', verbose_name='Trust Logo Section Links'),
        ),
    ]
