# Generated by Django 5.2.9 on 2026-05-21 09:02

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0020_workwithus_workwithusresumesubmission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workwithusresumesubmission',
            new_name='siteconfig__created_98ad67_idx',
            old_name='siteconfig_w_created_926eeb_idx',
        ),
        migrations.RenameIndex(
            model_name='workwithusresumesubmission',
            new_name='siteconfig__email_9ed7ad_idx',
            old_name='siteconfig_w_email_5a3fe9_idx',
        ),
        migrations.AddField(
            model_name='workwithus',
            name='collaboration_section_step1_image',
            field=models.FileField(blank=True, null=True, upload_to='workwithus/collaboration_steps/', verbose_name='Collaboration Section Step 1 Image'),
        ),
        migrations.AddField(
            model_name='workwithus',
            name='collaboration_section_step2_image',
            field=models.FileField(blank=True, null=True, upload_to='workwithus/collaboration_steps/', verbose_name='Collaboration Section Step 2 Image'),
        ),
        migrations.AddField(
            model_name='workwithus',
            name='collaboration_section_step3_image',
            field=models.FileField(blank=True, null=True, upload_to='workwithus/collaboration_steps/', verbose_name='Collaboration Section Step 3 Image'),
        ),
        migrations.AlterField(
            model_name='workwithus',
            name='main_content_section_tab1_description',
            field=tinymce.models.HTMLField(verbose_name='Main Content Section Tab 1 Description'),
        ),
        migrations.AlterField(
            model_name='workwithus',
            name='main_content_section_tab2_description',
            field=tinymce.models.HTMLField(verbose_name='Main Content Section Tab 2 Description'),
        ),
        migrations.AlterField(
            model_name='workwithus',
            name='main_content_section_tab3_description',
            field=tinymce.models.HTMLField(verbose_name='Main Content Section Tab 3 Description'),
        ),
    ]
