# Generated by Django 5.2.9 on 2026-05-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0021_rename_siteconfig_w_created_926eeb_idx_siteconfig__created_98ad67_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='top_teachers_description',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='top_teachers_list',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='top_teachers_title',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='logo_link_description',
            field=models.TextField(default='Logo Link Description', max_length=200, verbose_name='Logo Link List Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='logo_link_list',
            field=models.ManyToManyField(blank=True, related_name='logo_links', to='siteconfig.link', verbose_name='Logo Link List'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='logo_link_title',
            field=models.CharField(default='Logo Link Title', max_length=100, verbose_name='Logo Link List Title'),
            preserve_default=False,
        ),
    ]
