# Generated by Django 5.2.9 on 2026-05-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0022_remove_mainpage_top_teachers_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitenavbar',
            name='navbar_logo',
            field=models.FileField(help_text='Suggested Format: .svg', upload_to='navbar_images/logo/', verbose_name='Navbar Logo'),
        ),
    ]
