# Generated by Django 5.2.9 on 2026-06-02 07:45

import django.core.validators
import django.db.models.deletion
import tinymce.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Plan ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('picture', models.FileField(blank=True, null=True, upload_to='subscriptions/pictures/', verbose_name='Picture')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (Toman)')),
                ('new_price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discounted Price (0 = no discount)')),
                ('duration_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration (days)')),
                ('has_early_news_access', models.BooleanField(default=False, verbose_name='Early News Access')),
                ('has_quiz_access', models.BooleanField(default=False, verbose_name='Quiz Access')),
                ('online_class_limit', models.IntegerField(choices=[(0, 'No Access'), (4, 'Up to 4 meetings/month'), (8, 'Up to 8 meetings/month'), (12, 'Up to 12 meetings/month')], default=0, verbose_name='Online Class Meetings/Month')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('bought_by', models.ManyToManyField(blank=True, related_name='purchased_plans', to=settings.AUTH_USER_MODEL, verbose_name='Bought By')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(verbose_name='Started At')),
                ('ends_in', models.DateField(verbose_name='Ends In')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan', verbose_name='Plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
    ]
