# Generated by Django 5.2.9 on 2026-06-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='started_at',
            field=models.DateField(auto_now_add=True, verbose_name='Started At'),
        ),
    ]
