# Generated by Django 5.2.9 on 2026-06-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_usersubscription_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_free_course_access',
            field=models.BooleanField(default=False, verbose_name='Free Course Access'),
        ),
    ]
