# Generated by Django 5.2.9 on 2026-05-21 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Gallery ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('thumbnail', models.FileField(upload_to='gallery/thumbnails/', verbose_name='Thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GalleryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('embed', 'Embed')], max_length=10, verbose_name='Content Type')),
                ('image', models.FileField(blank=True, null=True, upload_to='gallery/content/images/', verbose_name='Image')),
                ('video', models.FileField(blank=True, null=True, upload_to='gallery/content/videos/', verbose_name='Video')),
                ('audio', models.FileField(blank=True, null=True, upload_to='gallery/content/audio/', verbose_name='Audio')),
                ('embed_code', models.TextField(blank=True, default='', verbose_name='Embed Code')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='gallery.gallery', verbose_name='Gallery')),
            ],
            options={
                'verbose_name': 'Gallery Content',
                'verbose_name_plural': 'Gallery Contents',
                'ordering': ('order', 'id'),
            },
        ),
    ]
