# Generated by Django 5.2.9 on 2026-02-26 03:15

import django.core.validators
import django.db.models.deletion
import tinymce.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Course ID')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('short_description', tinymce.models.HTMLField(verbose_name='Short Description')),
                ('long_description', tinymce.models.HTMLField(verbose_name='Long Description')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='courses/intros/', verbose_name='Course Intro Video')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (Toman)')),
                ('new_price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discounted Price (0 = no discount)')),
                ('extra_sells', models.PositiveIntegerField(default=0, verbose_name='Extra Sells (outside site)')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, verbose_name='Difficulty')),
                ('age_group', models.CharField(choices=[('kid', 'Kid'), ('teen', 'Teen'), ('adult', 'Adult'), ('all', 'All')], max_length=10, verbose_name='Age Group')),
                ('category', models.CharField(choices=[('naghme', 'Naghme'), ('hafeze', 'Hafeze'), ('andishe', 'Andishe')], max_length=20, verbose_name='Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('bought_by', models.ManyToManyField(blank=True, related_name='purchased_courses', to=settings.AUTH_USER_MODEL, verbose_name='Bought By')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Description')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('number_of_files', models.PositiveIntegerField(default=0, verbose_name='Number of Files')),
                ('number_of_videos', models.PositiveIntegerField(default=0, verbose_name='Number of Videos')),
                ('is_free', models.BooleanField(default=False, verbose_name='Free Preview')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('type', models.CharField(choices=[('video', 'Video'), ('note', 'Note'), ('attachment', 'Attachment')], max_length=20, verbose_name='Type')),
                ('file', models.FileField(upload_to='courses/episodes/', verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='courses.chapter', verbose_name='Chapter')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['chapter', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher', 'created_at'], name='courses_cou_teacher_6bc8f5_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['difficulty', 'age_group'], name='courses_cou_difficu_06686b_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='courses_cou_categor_fec4a4_idx'),
        ),
    ]
