# Generated by Django 5.2.9 on 2026-02-26 03:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='total_time',
            field=models.PositiveIntegerField(default=0, help_text='Time it takes to finish this course', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Time'),
        ),
        migrations.AddField(
            model_name='episode',
            name='counted',
            field=models.BooleanField(default=False, verbose_name='Counted'),
        ),
    ]
