# Generated by Django 5.2.9 on 2026-04-13 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_rating_course_total_time_episode_counted'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='If disabled purchasing items of this model will be disabled too.', verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_time',
            field=models.PositiveIntegerField(default=0, help_text='Time it takes to finish this course', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Time(H)'),
        ),
    ]
