# Generated by Django 5.2.9 on 2026-04-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_visible_alter_course_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='courses/images/', verbose_name='Course Image/Banner'),
        ),
    ]
