# Generated by Django 5.2.9 on 2026-05-05 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_courses', to=settings.AUTH_USER_MODEL, verbose_name='Saved By'),
        ),
    ]
