# Generated by Django 5.2.9 on 2026-05-12 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_saved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether user has completed this episode', verbose_name='Completed')),
                ('watch_count', models.PositiveIntegerField(default=1, help_text='Number of times user has watched this episode', verbose_name='Watch Count')),
                ('watch_duration', models.PositiveIntegerField(default=0, help_text='Total seconds watched (for video progress tracking)', verbose_name='Watch Duration (seconds)')),
                ('last_watched_at', models.DateTimeField(auto_now=True, verbose_name='Last Watched At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('course', models.ForeignKey(help_text='Denormalized for faster queries', on_delete=django.db.models.deletion.CASCADE, related_name='episode_progress', to='courses.course', verbose_name='Course')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.episode', verbose_name='Episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_progress', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Episode Progress',
                'verbose_name_plural': 'Episode Progress',
                'ordering': ['-last_watched_at'],
                'indexes': [models.Index(fields=['user', 'course'], name='courses_epi_user_id_8e9557_idx'), models.Index(fields=['user', '-last_watched_at'], name='courses_epi_user_id_fb7684_idx'), models.Index(fields=['course', 'is_completed'], name='courses_epi_course__2c55a0_idx')],
                'unique_together': {('user', 'episode')},
            },
        ),
    ]
