# Generated by Django 5.2.9 on 2026-05-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_episodeprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('telavat', 'Telavat'), ('tahfiz', 'Tahfiz'), ('tadabbor', 'Tadabbor')], max_length=20, verbose_name='Category'),
        ),
    ]
