# Generated by Django 5.2.9 on 2026-06-23 08:28

import django.core.validators
import django.db.models.deletion
import tinymce.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'Time Range',
                'verbose_name_plural': 'Time Ranges',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='InPersonClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='in_person_class/thumbnails/', verbose_name='Thumbnail')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('short_description', tinymce.models.HTMLField(verbose_name='Short Description')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (Toman)')),
                ('new_price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discounted Price (0 = no discount)')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('categories', models.ManyToManyField(blank=True, related_name='classes', to='in_person_class.category', verbose_name='Categories')),
                ('available_times', models.ManyToManyField(blank=True, related_name='classes', to='in_person_class.timerange', verbose_name='Available Times')),
            ],
            options={
                'verbose_name': 'In-Person Class',
                'verbose_name_plural': 'In-Person Classes',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='InPersonClassRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('price', models.PositiveIntegerField(verbose_name='Price (Toman)')),
                ('new_price', models.PositiveIntegerField(default=0, verbose_name='Discounted Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('bought_by', models.ManyToManyField(blank=True, related_name='in_person_class_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Bought By')),
                ('in_person_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='in_person_class.inpersonclass', verbose_name='In-Person Class')),
                ('time_range', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='in_person_class.timerange', verbose_name='Time Range')),
            ],
            options={
                'verbose_name': 'In-Person Class Registration',
                'verbose_name_plural': 'In-Person Class Registrations',
                'unique_together': {('in_person_class', 'time_range')},
            },
        ),
        migrations.AddIndex(
            model_name='inpersonclass',
            index=models.Index(fields=['is_visible', 'start_date'], name='in_person_c_is_visi_0b5f92_idx'),
        ),
    ]
