# Generated by Django 5.2.9 on 2026-06-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_person_class', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpersonclass',
            name='meeting_url',
            field=models.URLField(blank=True, null=True, verbose_name='Online Meeting URL'),
        ),
    ]
