# Generated by Django 5.2.9 on 2026-08-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_person_class', '0002_inpersonclass_meeting_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpersonclass',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacity per Time Slot (empty = unlimited)'),
        ),
    ]
